{% set name = "configobj" %}
{% set version = "5.0.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/configobj-{{ version }}.tar.gz
  sha256: 03c881bbf23aa07bccf1b837005975993c4ab4427ba57f959afdd9d1a2386848

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python
    - setuptools
    - pip
  run:
    - python
    - six

test:
  source_files:
    - src/tests/
  imports:
    - configobj
  commands:
    - pip check
    - python -m pytest src/tests/ -v  # [not win] 
    - python -m pytest src/tests/ -v -k "not test_detecting_line_endings_from_existing_files"  # [win]
  requires:
    - pip
    - pytest

about:
  home: https://github.com/DiffSK/configobj
  summary: Config file reading, writing and validation.
  description: |
    ConfigObj is a simple but powerful config file reader and writer: an ini
    file round tripper. Its main feature is that it is very easy to use, with a
    straightforward programmer's interface and a simple syntax for config files.
    It has lots of other features though:

    * Nested sections (subsections), to any level
    * List values
    * Multiple line values
    * Full Unicode support
    * String interpolation (substitution)
    * Integrated with a powerful validation system
        - including automatic type checking/conversion
        - and allowing default values
        - repeated sections

    * All comments in the file are preserved
    * The order of keys/sections is preserved
    * Powerful `unrepr` mode for storing/retrieving Python data-types
  license: BSD-3-Clause
  license_file: LICENSE
  license_family: BSD
  dev_url: https://github.com/DiffSK/configobj
  doc_url: https://configobj.readthedocs.io/

extra:
  skip-lints:
    - missing_wheel